name: battleships
description: BattleShips android game made using Flutter framework.
publish_to: "none"
version: 1.0.0

environment:
    sdk: ">=3.1.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    http: ^1.1.0
    shared_preferences: ^2.2.2
    provider: ^6.0.5

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/
